### ISSUE TITLE
Suggestion: An option to trim all consecutive empty lines from the start of the file

### ISSUE THREAD

**Issue by tpaananen** [ArnaudMarcille/EmptyLineExtension#10]
It would be useful if there was an option to trim all consecutive empty lines from the start of the file regardless of the "number of lines" -setting.
Maybe with an option in the settings (on/off) if there are use cases where one wants to leave empty line(s) on top of the file.

With current implementation there is at least one empty line left (when at least one exists) on top of the file unless setting the "number of lines" option to zero which basically cannot be used in code files at least.

**Comment by ArnaudMarcille** [comment]
Hello,
Indeed there is no way to allow some lines on the top of the file today. The only way do do that manually is to disable the trim on save, and trim with a selection (select the lines to trim in the document). 

If I have correctly understand your issue, adding a setting for ignore the lines from the top of the document will be ok?

**Comment by tpaananen** [comment]
Hi,

Yes so what I meant was basically as follows:

A new setting, lets call it "Remove all consecutive empty lines from the beginning of file" [Yes\No]

When Yes, recardless of the other setting "Allowed lines (default 1)", the new logic would remove empty lines from the beginning of the file until it finds a non-empty line. So leaving no empty lines between start of the file and first non-empty line.

When No, current implementation applies as it is now.

**Comment by ArnaudMarcille** [comment]
Done il last release

**Comment by tpaananen** [comment]
Hi,

I think the new setting in the latest release is doing the opposite what was requested in this issue? I'm assuming the setting was added due to this issue? I'm not sure how it solves this particular issue.

So to put it in context the new setting, when applied, is ignoring the start of the file completely (removing no lines from the beginning) whereas the feature request was to add a setting to **remove all** empty lines from the beginning regardless of the setting "Allowed lines".

Thanks

**Comment by ArnaudMarcille** [comment]
ho ! A big fail from me! Will be in next release

**Comment by ArnaudMarcille** [comment]
Can you try the 1.3.1? (updated on the marketplace)

**Comment by tpaananen** [comment]
1.3.1 works in normal cases, but when the file has only empty lines, then Visual Studio hangs when the empty lines are about get removed. If the new feature is disabled, does not hang in the same case.

**Comment by ArnaudMarcille** [comment]
Fixed in 1.3.2.
