### ISSUE TITLE
1.3.0 can't work right

### ISSUE THREAD

**Issue by zxgamekingdom** [ArnaudMarcille/EmptyLineExtension#13]
When I set allowed lines to 0 , then right click to select remove emtpy lines , my code hasn't changed , and empty lines haven't been removed .

Microsoft Visual Studio Enterprise 2019 16.8.6

**Comment by ArnaudMarcille** [comment]
Indeed. I've found the problem, I'm working on it.

**Comment by ArnaudMarcille** [comment]
Can you try the 1.3.1? (updated on the marketplace)

**Comment by zxgamekingdom** [comment]
Yes, the problem has disappeared. Thank you.
