### ISSUE TITLE
Update for Visual Studio 2022

### ISSUE THREAD

**Issue by StanislavPrusac** [ArnaudMarcille/EmptyLineExtension#18]
Was wondering if there are plans to update this extension for VS 2022? Migration guide can be found here: https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension

**Comment by ArnaudMarcille** [comment]
Yes I was planning to do this update soon, thanks for the guide !

**Comment by ArnaudMarcille** [comment]
Done
