### ISSUE TITLE
Disable auto format on document save not working in Visual Studio 2022 

### ISSUE THREAD

**Issue by StanislavPrusac** [ArnaudMarcille/EmptyLineExtension#19]
When in Tools->Option-> Empty Line extension Settings disable this property:
"Enable auto format on document save" 
the extension still deletes double lines, when CTRL+S is selected to saves the document.

I would like to have the option not to delete double lines when saving the document, because in some documents I need and want to keep double lines.

Thank you for the useful extension!

**Comment by ArnaudMarcille** [comment]
Hello,

thanks for sharing me this issue, I will fix the settings error.

For managing double lines, you can use the different settings of the extension: 
you can allow 2 lines by default 
![image](https://user-images.githubusercontent.com/28567558/187682622-46b4b2d5-2360-4b2e-a432-6e646310a12f.png)

you can also uses the regex tool :
![image](https://user-images.githubusercontent.com/28567558/187685237-72bede44-11f5-4e23-a06c-ea4763cfe509.png)
the last regex matching will be used to manage custom rule, in this case, all .cs file will have 2 rows allowed, and every over file 1.

**Comment by ArnaudMarcille** [comment]
@StanislavPrusac , A fix have been pushed on the visual studio store, let me know if the issue is fixed from your side.

Thanks again

**Comment by StanislavPrusac** [comment]
@ArnaudMarcille  thanks for the quick fix.
1. I installed the new version and tested it.
Everything about the login bug is working properly.
Thank you!

2. I also noticed a minor UI bug.
On files with the extension, html, css, json, when you right-click in a file in the menu options "Remove empty lines" are not displayed 
On those files, I can remove empty line via shortcut and it works normally on save file.

With other extensions like, cs, cshtml, js, txt, the menu option is displayed.

**Comment by ArnaudMarcille** [comment]
I will check why the menu option does not work on this files, thanks for the information!

**Comment by StanislavPrusac** [comment]
I found another bug, maybe it is related to the last change, so I will describe it here.

On any command to delete blank lines, only those lines that are visible on the screen are deleted.
It also does not work when the entire text is selected. 
It also erases only the empty lines that are visible on the screen.
I tried under different settings.
I am using Visual Studio 2022 Version 17.4.0 Preview 1.0

**Comment by ArnaudMarcille** [comment]
An update have been released for manage all the document.

The second issue (Extension menu do not display itself in some doucment (like json, html, css)) is due to a weird management from visual studio (for example, .html file do not have a file path...). 
I will manage it in another version due to research time.

Let me know if the range issue is solved from your side :)

**Comment by StanislavPrusac** [comment]
I tested the new version and everything works exactly as it should.
As far as I'm concerned, this bug can be closed.
Thank you very much and well done.
