### ISSUE TITLE
Suggestion: specify the “Allowed lines” setting per file type/mask

### ISSUE THREAD

**Issue by HamRusTal** [ArnaudMarcille/EmptyLineExtension#6]
**Motivation:** in my C++ code, I want to avoid multiple empty lines, so I'm fine with the default value of 1; but when I edit e.g. Python code in Visual Studio (for which it is well suited too), I want double empty lines preserved as [specified by PEP 8](https://www.python.org/dev/peps/pep-0008/#blank-lines), and of course I want the extra empty lines removed automatically. Hence the need for a per-language/type setting.

**Possible UI:** it could be a list of pairs (represented as a two-column table): file name (or even full path) mask (glob or even regexp) and number of consecutive empty lines to keep. So in my  case it would be:
```
*.py	2
*	1
```

**Comment by ArnaudMarcille** [comment]
Hello,

I'ts a good idea, it can be very usefull.
And what do you think about a list of pair Regex / number, it can allow you to use different settings for file names, file path, or extension. Or do you prefer it by extension?

**Comment by HamRusTal** [comment]
Regexps are totally fine!
If they are matched against file's **full path**, then it will allow having per-project settings, e.g.
```
/Path\\to\\my\\work\\Proj1\\.*\.(cpp|h)$/	1
/Path\\to\\my\\work\\Proj2\\.*\.(cpp|h)$/	2
/\.py$/	2
//	1
```
