### ISSUE TITLE
Suggestion: put all removed lines into a single Undo/Redo step

### ISSUE THREAD

**Issue by HamRusTal** [ArnaudMarcille/EmptyLineExtension#7]
When the empty lines are removed by the extension (especially automatically), the scale of the change is sometimes much larger than expected (which is exposed e.g. by Git Diff), so I need to undo the removal. But every line removal is registered as a separate Undo step, so the process becomes tedious very soon (and the Undo/Redo history get contaminated with dozens of “Smart Enter” items). It would be great if the entire cleanup operation was represented by a single Undo/Redo step.

**Comment by ArnaudMarcille** [comment]
Hello, 
yeah, it can be usefull, i've started search about this.

**Comment by ArnaudMarcille** [comment]
It's done, I will push it in the store at the same time than the issue #6
